### ISSUE TITLE
How to set timeout on the tcp operation

### ISSUE THREAD

**Issue by chmorgan** [werdl/quickhttp#1]
It looks like the way to do this is via TcpStream::connect_timeout() but send() is using TcpStream::connect(). Any interest in a change that could support setting a timeout? I'm not sure how one might do this but wanted to see if there was any interest in the change or perhaps if I'm missing something and its already possible.

**Comment by werdl** [comment]
No, I don't think this is currently possible. I will implement it soon.

**Comment by werdl** [comment]
This now implemented with suggested fix (change function call in `Builder::send()`. Thanks for the pointer!
